"""Dataset statistics report — feeds docs/data-card and the dataset_sources table.

Outputs a markdown table + CSV per dataset under reports/datasets/ (generated
artifacts, gitignored; re-generated by `python -m ml.data.cli stats`).
"""

import csv
import json
from datetime import UTC, datetime
from pathlib import Path

SPLIT_NAMES = ("train", "val", "test")


def generate_stats(split_dir: Path, out_dir: Path) -> dict:
    split_dir, out_dir = Path(split_dir), Path(out_dir)
    manifest = json.loads((split_dir / "split_manifest.json").read_text(encoding="utf-8"))
    dataset = manifest["dataset"]
    classes = sorted(
        {c for name in SPLIT_NAMES for c in manifest["splits"][name]["classes"]}
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"{dataset}-stats.md"
    csv_path = out_dir / f"{dataset}-stats.csv"

    def cell(name: str, cls: str) -> int:
        return manifest["splits"][name]["classes"].get(cls, 0)

    totals = {name: manifest["splits"][name]["count"] for name in SPLIT_NAMES}
    grand_total = sum(totals.values())

    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["class", *[f"{n}_count" for n in SPLIT_NAMES], "total"])
        for cls in classes:
            row = [cell(name, cls) for name in SPLIT_NAMES]
            writer.writerow([cls, *row, sum(row)])
        writer.writerow(["TOTAL", *totals.values(), grand_total])

    lines = [
        f"# Dataset stats — {dataset} (split {manifest['version']})",
        "",
        f"Generated: {datetime.now(UTC).isoformat(timespec='seconds')} · seed {manifest['seed']} · ratios {'/'.join(str(int(r * 100)) for r in manifest['ratios'])}",
        "",
        f"Source: `{manifest['images_root']}`",
        "",
        "| condition (disease_id) | train | val | test | total |",
        "|---|---:|---:|---:|---:|",
    ]
    for cls in classes:
        row = [cell(name, cls) for name in SPLIT_NAMES]
        lines.append(f"| {cls} | {row[0]} | {row[1]} | {row[2]} | {sum(row)} |")
    lines.append(f"| **TOTAL** | **{totals['train']}** | **{totals['val']}** | **{totals['test']}** | **{grand_total}** |")
    lines += [
        "",
        "## Skipped class folders (recorded, not silent)",
        "",
        f"- Unmapped / out of V1 scope: `{json.dumps(manifest['skipped']['unmapped'])}`",
        f"- Explicitly excluded (e.g. background): `{json.dumps(manifest['skipped']['excluded'])}`",
        "",
        "Policy: stratified image-level split; without-augmentation source only; same seed reproduces this byte-identically.",
    ]
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    largest = max(classes, key=lambda c: sum(cell(n, c) for n in SPLIT_NAMES))
    smallest = min(classes, key=lambda c: sum(cell(n, c) for n in SPLIT_NAMES))
    return {
        "dataset": dataset,
        "grand_total": grand_total,
        "class_count": len(classes),
        "splits": totals,
        "largest_class": largest,
        "smallest_class": smallest,
        "md": str(md_path),
        "csv": str(csv_path),
    }
