import type { Metadata } from "next";

import ModelInfoLive from "@/components/ModelInfoLive";

export const metadata: Metadata = {
  title: "Model information",
  description:
    "Live model registry: version, status, confidence bands, supported crops — plus the standing evaluation and honesty policy.",
};

const POLICY = [
  {
    heading: "Evaluation policy",
    body: "Metrics are generated by the evaluation pipeline into reports/model_evaluation/ and published in the model card (docs/06) — including out-of-distribution results on PlantDoc field imagery. Poor results get reported, not hidden. Market-facing accuracy claims always quote in-domain and out-of-distribution figures together.",
  },
  {
    heading: "What predictions mean",
    body: "Every prediction is a 'Suspected' condition at a stated confidence with an uncertainty score — decision support requiring human verification, never a definitive diagnosis. No chemical product, brand or dosage guidance is provided, anywhere in the product.",
  },
  {
    heading: "Uncertainty & explainability",
    body: "Each prediction reports predictive-entropy uncertainty and a Grad-CAM overlay. Highlighted regions contributed strongly to the prediction — they are not a guarantee of disease location and not causal proof.",
  },
  {
    heading: "Versioning & reproducibility",
    body: "Every prediction records model name, model version, dataset version and threshold version, enabling honest audits. The demo (synthetic sample) model is flagged on every surface — silently upgraded claims are a bug; report them.",
  },
];

export default function ModelInformationPage() {
  return (
    <div className="container-shell max-w-4xl py-10">
      <p className="eyebrow">Transparency</p>
      <h1 className="section-title">Model information</h1>
      <p className="section-lede">
        Live registry data from this deployment, plus the standing policy that governs every claim the product
        makes.
      </p>
      <div className="mt-8">
        <ModelInfoLive />
      </div>
      <div className="mt-10 space-y-8">
        {POLICY.map((section) => (
          <section key={section.heading}>
            <h2 className="text-lg font-semibold text-stone-900">{section.heading}</h2>
            <p className="mt-2 text-sm leading-7 text-stone-600">{section.body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
